### ISSUE TITLE
использовать String.format()

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#1]
https://github.com/ErmakMichael/JD1/blob/592a9e2c276d8e7b4ca14eb3512301df3e628776/src/com/intexsoft/task2/Task2.java#L18

наверное это было написано до того, как я про него рассказал. но на всякий случай еще раз напоминаю

**Comment by ErmakMichael** [comment]
Верно говоришь. Уже использую String.format()
