### ISSUE TITLE
При объявлении типа лучше использовать List,а не ArrayList (вспоминай почему)

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#12]
https://github.com/ErmakMichael/JD1/blob/10bafe3795dd8ab1f52815d2218745983fb4c685/src/com/itacademy/task26/Task26.java#L10

**Comment by ErmakMichael** [comment]
Не было меня на этой лекции(уезжал по семейным).  
Как я понял ArrayList дочерний класс и он унаследован от List и имеет все те же методы и свойства.

Если есть возможность вкратце описать отличие?

**Comment by dzhivushko** [comment]
суть в том, что можно менять ArrayList на LinkedList в одном месте и дальше весь код останется неизменным. если писать, как сделал ты, то возможно придется менять в 10+ местах.
если коротко, то все типы перменных (при объявлении, в сигнатурах методов, конструкторах) должны быть как можно более абстрактные (ну не Object конечно). конкретный тип указывается только там где ты пишешь 'new'.
