### ISSUE TITLE
имя метода

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#2]
https://github.com/ErmakMichael/JD1/blob/592a9e2c276d8e7b4ca14eb3512301df3e628776/src/com/intexsoft/task4/Task4.java#L19

я не знаю как звучит по-русски то, что ты планировал написать. но есть подозрения, что метод назван некорретно. напоминаю, что должен быть глагол. т.е. что-то типа calculateSomething() , isSomething(), getSomething() И т.п.
вроде у тебя не глагол... и потому не ясно что там вообще

**Comment by ErmakMichael** [comment]
Имел ввиду диагональ прямоугольника, но в любом случае это не глагол. Буду внимательнее.
