### ISSUE TITLE
разное...

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#4]
https://github.com/ErmakMichael/JD1/blob/592a9e2c276d8e7b4ca14eb3512301df3e628776/src/com/intexsoft/task7/Task7.java#L5-L32

https://github.com/PitGarin/JD1/issues/2
https://github.com/PitGarin/JD1/issues/8
https://github.com/PitGarin/JD1/issues/10

пересмотри эти замечания у другого человека. у тебя все аналогично (задания могут быть разные - не именно в этом все встречаться)

**Comment by ErmakMichael** [comment]
Уже осознал что русский вообще нету смысла использовать.
