### ISSUE TITLE
замечания

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#6]
https://github.com/ErmakMichael/JD1/blob/10bafe3795dd8ab1f52815d2218745983fb4c685/src/com/itacademy/task21/Task21.java#L5-L36

имена методов всегда(!!!) пишутся   с маленькой буквы. с большой только имена классов и констант - больше ничего

методы возвращают значения. а зачем? "на всякий случай"? так не бывает. если бы назвал метод getExecutionTime, то он должен возвращать (при этом ничего больше не делать - не печатать результат). а если ты внутри метода проводишь тест, печатаешь результат + назвал ты его соответственно, то там не должно быть никакого return

**Comment by ErmakMichael** [comment]
Почему написал с большой? Для меня самого это загадка. Методы сделал void, соответственно  return не нужны.
