### ISSUE TITLE
get должен что-то возвращать

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#8]
https://github.com/ErmakMichael/JD1/blob/10bafe3795dd8ab1f52815d2218745983fb4c685/src/com/itacademy/task23/Task23.java#L11

метод надо либо просто переименовать(скорее всего), либо переписать. 
если метод что-то делает и ничего не возвращает - э то doSomething(). а если getSomething, то он должен вернуть something

**Comment by ErmakMichael** [comment]
Переименовал
