### ISSUE TITLE
почему свойство protected?

### ISSUE THREAD

**Issue by dzhivushko** [ErmakMichael/JD1#9]
https://github.com/ErmakMichael/JD1/blob/10bafe3795dd8ab1f52815d2218745983fb4c685/src/com/itacademy/task24/ApplianceForKitchen.java#L5

**Comment by ErmakMichael** [comment]
Делал для того чтобы дочерний класс мог унаследовать, но потом понял, что через public getter могу дергать private свойства.  Сделал приватными все свойства.
